### ISSUE TITLE
bibparse

### ISSUE THREAD

**Issue by keithbriggs** [tdegeus/bibparse#2]
The name of this project clashes with bibparse from the classic btparse-0.35 project.

**Comment by tdegeus** [comment]
Thanks for pointing this out. I was not aware. Do you have a suggestion for another name?

**Comment by keithbriggs** [comment]
It's tricky, as there have been many similar projects in the past with similar names.


If its function is not merely to parse, but mainly to clean, maybe something like bibtexclean?


Keith

________________________________

**Comment by tdegeus** [comment]
To avoid naming conflict I have moved this script to https://github.com/tdegeus/GooseBib. There I have started introducing some more functionality.
